# If set to "true", Maintenance Mode Will Be Active
Maintenance_Mode_Active: false
# Change everything inside of the "" below to set your own message
Maintenance_Mode_Message: "§aGuardian §7>> §fThis server is Currently Down For §cMaintenance"
